//=================================================================================================================================
//
// Author: Maurice Ribble
//         3D Application Research Group
//         ATI Research, Inc.
//
// Definitions for the GenFont class.  This class takes font data generated by the AngelCode Bitmap Font Generator
// (http://www.angelcode.com/products/bmfont/) and converts it into a header file that can be read by the Font class.
//
//=================================================================================================================================
// $Id: //depot/3darg/Tools/Handheld/esTestApps/common/GenFont.h#1 $ 
// 
// Last check-in:  $DateTime: 2008/01/23 11:45:40 $ 
// Last edited by: $Author: dginsbur $
//=================================================================================================================================
//   (C) ATI Research, Inc. 2006 All rights reserved. 
//=================================================================================================================================

#include "ArgDefines.h"

class GenFont
{
public:
   /// \brief Creates the header file from the font data generated by AngelCode
   bool CreateFontFile( char8* fontImageFile, char8* fontDataFile, char8* outputFontName, int32 fontNum );
private:
};